FROM bellsoft/alpaquita-linux-base:stream-glibc

ENV SYS_ARCH "$(apk --print-arch)"

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'

RUN apk add --no-cache tzdata --virtual .build-deps \
    && apk add curl binutils zstd tmux \
    && case $SYS_ARCH in \
        amd64|x86_64) \
            PLAYIT_SHA256="1a0da96f9f2ba2d5fa875c009ed01c2bd037e23777ba06fecfc5ea74cc23388f" \
            PLAYIT_URL="https://github.com/playit-cloud/playit-agent/releases/download/v0.15.22/playit-linux-amd64" \
        ;; \
        aarch64|arm64) \
            PLAYIT_SHA256="f213d16e4b1cae935fd48885e9b3a9a4e6ba10bc47ba91caa3585bd240e71d09" \
            PLAYIT_URL="https://github.com/playit-cloud/playit-agent/releases/download/v0.15.22/playit-linux-aarch64" \
        ;; \
        *) \
            echo "Unsupported arch: $SYS_ARCH";\
            exit 1; \
        ;; \
    esac \
    && curl -LfsS ${PLAYIT_URL} -o /tmp/playit \
    && echo "${PLAYIT_SHA256} */tmp/playit" | sha256sum -c - \
    && mkdir -p /opt/playit/bin \
    && mv /tmp/playit /opt/playit/bin \
    && ln -s /opt/playit/bin/playit /usr/bin/playit

ENV JAVA_VERSION jdk-17.0.9+9_openj9-0.41.0

RUN set -eux; \
    apk add --no-cache --virtual .fetch-deps; \
    case $SYS_ARCH in \
       amd64|x86_64) \
         SHA="1caf409f33f7738efe37742197525b5ae6244d6383b2017e7b8e925dc0b6a329"; \
         JDK_URL="https://github.com/ibmruntimes/semeru17-binaries/releases/download/jdk-17.0.9%2B9_openj9-0.41.0/ibm-semeru-open-jre_x64_linux_17.0.9_9_openj9-0.41.0.tar.gz"; \
         ;; \
        aarch64|arm64) \
         SHA="9760aa27a5790a8c20a702ff5f036535f3df51d3fb291bb5254b5ae76e096bad" \
         JDK_URL="https://github.com/ibmruntimes/semeru17-binaries/releases/download/jdk-17.0.9%2B9_openj9-0.41.0/ibm-semeru-open-jre_aarch64_linux_17.0.9_9_openj9-0.41.0.tar.gz" \
        ;; \
       *) \
         echo "Unsupported arch: $SYS_ARCH"; \
         exit 1; \
         ;; \
    esac; \
    curl -LfsSo /tmp/openjdk.tar.gz ${JDK_URL}; \
    echo "$SHA */tmp/openjdk.tar.gz" | sha256sum -c -; \
    mkdir -p /opt/java/openjdk; \
    cd /opt/java/openjdk; \
    tar -xf /tmp/openjdk.tar.gz --strip-components=1; \
    apk del --purge .fetch-deps; \
    rm -rf /var/cache/apk/*; \
    rm -rf /tmp/openjdk.tar.gz;

ENV JAVA_HOME=/opt/java/openjdk \
    PATH="/opt/java/openjdk/bin:$PATH"
ENV JAVA_TOOL_OPTIONS="-XX:+IgnoreUnrecognizedVMOptions -XX:+IdleTuningGcOnIdle"
