FROM bellsoft/alpaquita-linux-base:stream-glibc

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'

RUN apk add --no-cache tzdata --virtual .build-deps \
    && apk add curl binutils zstd tmux \
    && PLAYIT_SHA256="1a0da96f9f2ba2d5fa875c009ed01c2bd037e23777ba06fecfc5ea74cc23388f" \
    && PLAYIT_URL="https://github.com/playit-cloud/playit-agent/releases/download/v0.15.22/playit-linux-amd64" \
    && curl -LfsS ${PLAYIT_URL} -o /tmp/playit \
    && echo "${PLAYIT_SHA256} */tmp/playit" | sha256sum -c - \
    && mkdir -p /opt/playit/bin \
    && mv /tmp/playit /opt/playit/bin \
    && ln -s /opt/playit/bin/playit /usr/bin/playit

ENV JAVA_VERSION jdk-21.0.4+7_openj9-0.46.0

RUN set -eux; \
    SYS_ARCH=$(apk --print-arch); \
    apk add --no-cache --virtual .fetch-deps; \
    case $SYS_ARCH in \
       amd64|x86_64) \
         SHA="6db728e08b4cba2490e720cf4e11d13096f6ecfe9429a60a996128c4d629a26e"; \
         JDK_URL="https://github.com/ibmruntimes/semeru21-binaries/releases/download/jdk-21.0.4+7_openj9-0.46.0/ibm-semeru-open-jre_x64_linux_21.0.4_7_openj9-0.46.0.tar.gz"; \
         ;; \
       *) \
         echo "Unsupported arch: $SYS_ARCH"; \
         exit 1; \
         ;; \
    esac; \
    curl -LfsSo /tmp/openjdk.tar.gz $JDK_URL; \
    echo "$SHA */tmp/openjdk.tar.gz" | sha256sum -c -; \
    mkdir -p /opt/java/openjdk; \
    cd /opt/java/openjdk; \
    tar -xf /tmp/openjdk.tar.gz --strip-components=1; \
    apk del --purge .fetch-deps; \
    rm -rf /var/cache/apk/*; \
    rm -rf /tmp/openjdk.tar.gz;

ENV JAVA_HOME=/opt/java/openjdk \
    PATH="/opt/java/openjdk/bin:$PATH"
ENV JAVA_TOOL_OPTIONS="-XX:+IgnoreUnrecognizedVMOptions -XX:+IdleTuningGcOnIdle -Xshareclasses:name=openj9_system_scc,cacheDir=/opt/java/.scc,readonly,nonFatal"

RUN set -eux; \
    apk add --no-cache --virtual .scc-deps; \
    unset OPENJ9_JAVA_OPTIONS; \
    SCC_SIZE="50m"; \
    DL_PATH_TOMCAT=/tmp/tomcat; \
    IN_PATH_TOMCAT=/opt/tomcat-home; \
    TOMCAT_SHA="f6b875f656239d0709dae3fe55ce413e72ab6fbbbc1a594526c019c8fb169def"; \
    TOMCAT_DL_URL="https://archive.apache.org/dist/tomcat/tomcat-11/v11.0.0-M24/bin/apache-tomcat-11.0.0-M24.tar.gz"; \
    \
    mkdir -p "${DL_PATH_TOMCAT}" "${IN_PATH_TOMCAT}"; \
    curl -LfsSo "${DL_PATH_TOMCAT}"/tomcat.tar.gz "${TOMCAT_DL_URL}"; \
    echo "${TOMCAT_SHA} *${DL_PATH_TOMCAT}/tomcat.tar.gz" | sha256sum -c -; \
    tar -xf "${DL_PATH_TOMCAT}"/tomcat.tar.gz -C "${IN_PATH_TOMCAT}" --strip-components=1; \
    rm -rf "${DL_PATH_TOMCAT}"; \
    \
    java -Xshareclasses:name=dry_run_scc,cacheDir=/opt/java/.scc,bootClassesOnly,nonFatal,createLayer -Xscmx$SCC_SIZE -version; \
    export OPENJ9_JAVA_OPTIONS="-Xshareclasses:name=dry_run_scc,cacheDir=/opt/java/.scc,bootClassesOnly,nonFatal"; \
    "${IN_PATH_TOMCAT}"/bin/startup.sh; \
    sleep 5; \
    "${IN_PATH_TOMCAT}"/bin/shutdown.sh -force; \
    sleep 15; \
    FULL=$( (java -Xshareclasses:name=dry_run_scc,cacheDir=/opt/java/.scc,printallStats 2>&1 || true) | awk '/^Cache is [0-9.]*% .*full/ {print substr($3, 1, length($3)-1)}'); \
    DST_CACHE=$(java -Xshareclasses:name=dry_run_scc,cacheDir=/opt/java/.scc,destroy 2>&1 || true); \
    SCC_SIZE=$(echo $SCC_SIZE | sed 's/.$//'); \
    SCC_SIZE=$(awk "BEGIN {print int($SCC_SIZE * $FULL / 100.0)}"); \
    [ "${SCC_SIZE}" -eq 0 ] && SCC_SIZE=1; \
    SCC_SIZE="${SCC_SIZE}m"; \
    java -Xshareclasses:name=openj9_system_scc,cacheDir=/opt/java/.scc,bootClassesOnly,nonFatal,createLayer -Xscmx$SCC_SIZE -version; \
    unset OPENJ9_JAVA_OPTIONS; \
    \
    export OPENJ9_JAVA_OPTIONS="-Xshareclasses:name=openj9_system_scc,cacheDir=/opt/java/.scc,bootClassesOnly,nonFatal"; \
    "${IN_PATH_TOMCAT}"/bin/startup.sh; \
    sleep 5; \
    "${IN_PATH_TOMCAT}"/bin/shutdown.sh -force; \
    sleep 5; \
    FULL=$( (java -Xshareclasses:name=openj9_system_scc,cacheDir=/opt/java/.scc,printallStats 2>&1 || true) | awk '/^Cache is [0-9.]*% .*full/ {print substr($3, 1, length($3)-1)}'); \
    echo "SCC layer is $FULL% full."; \
    rm -rf "${IN_PATH_TOMCAT}"; \
    if [ -d "/opt/java/.scc" ]; then \
          chmod -R 0777 /opt/java/.scc; \
    fi; \
    \
    apk del --purge .scc-deps; \
    rm -rf /var/cache/apk/*; \
    echo "SCC generation phase completed";